version: '3'

services:
  with-docker-multi-env-staging:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: sugar-dating-fe-staging
    ports:
      - '3002:3000'
